# Generated by Django 3.1.3 on 2020-12-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0003_auto_20201210_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AlterModelOptions(
            name='external',
            options={},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
    ]
