# Generated by Django 3.1.3 on 2020-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0004_auto_20201223_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
