# Generated by Django 3.1.3 on 2020-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0005_event_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Can be delayed', 'Can be delayed'), ('Unimportant', 'Unimportant')], max_length=200, null=True),
        ),
    ]
