# Generated by Django 3.1.3 on 2020-12-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0006_auto_20201223_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='person_in_charge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_assistant.myuser'),
        ),
    ]
