# Generated by Django 3.1.3 on 2020-12-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0007_event_person_in_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'permissions': (('can_view_the_travel_page', 'Permission to view the travel page'),)},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': (('can_view_the_travel_page', 'Permission to view the travel page'),)},
        ),
    ]
