# Generated by Django 3.1.3 on 2020-12-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0008_auto_20201224_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'permissions': (('can_view_the_travel_page', 'Access travel page'),)},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': (('can_view_the_travel_page', 'Access travel page'),)},
        ),
    ]
