# Generated by Django 3.1.3 on 2020-12-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0009_auto_20201224_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': (('can_view_the_travel_page', 'Access travel page'), ('can_view_schedule_page', 'Access schedule page'))},
        ),
    ]
