# Generated by Django 3.1.3 on 2020-12-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0010_auto_20201224_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': (('can_view_schedule_page', 'Access schedule page'),)},
        ),
    ]
