# Generated by Django 3.1.3 on 2020-12-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0012_auto_20201224_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
