# Generated by Django 3.1.3 on 2020-12-24 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_assistant', '0013_auto_20201224_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='votes',
            field=models.ManyToManyField(related_name='trip_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
