# Generated by Django 3.1.3 on 2020-12-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0014_measurement_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Awaiting approval', 'Awaiting approval')], max_length=200, null=True),
        ),
    ]
