# Generated by Django 3.1.3 on 2020-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0015_measurement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Awaiting approval', 'Awaiting approval')], default='Awaiting approval', max_length=200, null=True),
        ),
    ]
