# Generated by Django 3.1.3 on 2020-12-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0016_auto_20201226_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_item',
            name='status',
            field=models.CharField(choices=[('Task done', 'Task done'), ('Task not yet done', 'Task not yet done')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child_item',
            name='category',
            field=models.CharField(choices=[('To read', 'To read'), ('To watch', 'To watch'), ('To buy', 'To buy'), ('To do', 'To do')], max_length=200, null=True),
        ),
    ]
