# Generated by Django 3.1.3 on 2020-12-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0017_auto_20201226_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_item',
            name='status',
            field=models.CharField(choices=[('Task done', 'Task done'), ('Task not done yet', 'Task not done yet')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Personal_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Task done', 'Task done'), ('Task not done yet', 'Task not done yet')], max_length=200, null=True)),
                ('person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_assistant.myuser')),
            ],
        ),
    ]
