# Generated by Django 3.1.3 on 2020-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0018_auto_20201226_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_event',
            name='status',
            field=models.CharField(choices=[('Task done', 'Task done'), ('Task not done yet', 'Task not done yet')], default='Task not done yet', max_length=200, null=True),
        ),
    ]
