# Generated by Django 3.1.3 on 2020-12-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0019_auto_20201226_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='external',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='External',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
