# Generated by Django 3.1.3 on 2020-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0020_auto_20201226_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('External', 'External')], max_length=200, null=True),
        ),
    ]
