# Generated by Django 3.1.3 on 2020-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0021_myuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
