# Generated by Django 3.1.3 on 2020-12-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_assistant', '0022_myuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password',
        ),
    ]
